version: '3.7'

services:
    dind:
        image: docker:dind
        command: dockerd --icc=false --userns-remap=default
        environment:
            - DOCKER_HOST=unix://var/run/docker.sock
        volumes:
            - type: volume
              source: sock
              target: /var/run
        privileged: true
    api:
        build: .
        command: python -u setup.py
        volumes:
            - type: bind
              source: .
              target: /api
            - type: volume
              source: sock
              target: /var/run
        ports:
            - "5000:5000"
        depends_on:
            - dind
    nginx:
        image: nginx
        depends_on:
            - api
        volumes:
            - type: bind
              source: ./api.conf
              target: /etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

volumes:
    sock:
    
